version: '3.8'
services:
  backend:
    build: ./backend
    container_name: truegate-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
      - PORT=5000
      # Add other environment variables as needed
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    container_name: truegate-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
