version: '3.8'

services:
  backend:
    build: ./backend
    container_name: truegate-backend
    expose:
      - "5000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
      - PORT=5000
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: truegate-frontend
    expose:
      - "80"
    depends_on:
      - backend
    restart: unless-stopped
