services:
  backend:
    build: ./backend
    container_name: truegate-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
      - PORT=5000
    restart: unless-stopped
    networks:
      - truegate-network

  frontend:
    build: ./frontend
    container_name: truegate-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
    restart: unless-stopped
    networks:
      - truegate-network
    depends_on:
      - backend

networks:
  truegate-network:
    driver: bridge


