name: Deploy TrueGate Fullstack on Main

on:
  push:
    branches:
      - main
      - feature/ci-cd
  pull_request:
    branches:
      - main
      - feature/ci-cd

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd TrueGate
            sudo git pull origin main
            sudo docker compose down
            sudo docker compose up -d --build
